# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.pb_collectInfo = QtWidgets.QPushButton(Form)
        self.pb_collectInfo.setGeometry(QtCore.QRect(10, 520, 201, 61))
        self.pb_collectInfo.setObjectName("pb_collectInfo")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(240, 10, 251, 16))
        self.label_title.setObjectName("label_title")
        self.pb_checkInfo = QtWidgets.QPushButton(Form)
        self.pb_checkInfo.setGeometry(QtCore.QRect(560, 520, 181, 61))
        self.pb_checkInfo.setObjectName("pb_checkInfo")
        self.label_capture = QtWidgets.QLabel(Form)
        self.label_capture.setGeometry(QtCore.QRect(20, 50, 520, 440))
        self.label_capture.setMinimumSize(QtCore.QSize(520, 440))
        self.label_capture.setMaximumSize(QtCore.QSize(520, 440))
        self.label_capture.setText("")
        self.label_capture.setObjectName("label_capture")
        self.pb_takePhoto = QtWidgets.QPushButton(Form)
        self.pb_takePhoto.setGeometry(QtCore.QRect(230, 520, 141, 61))
        self.pb_takePhoto.setObjectName("pb_takePhoto")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(400, 550, 91, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_face_num = QtWidgets.QLabel(Form)
        self.label_face_num.setGeometry(QtCore.QRect(400, 520, 81, 16))
        self.label_face_num.setObjectName("label_face_num")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(560, 40, 319, 459))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 317, 457))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_face_num_2 = QtWidgets.QLabel(Form)
        self.label_face_num_2.setGeometry(QtCore.QRect(770, 520, 81, 16))
        self.label_face_num_2.setObjectName("label_face_num_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(770, 550, 91, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_collectInfo.setText(_translate("Form", "开始采集"))
        self.label_title.setText(_translate("Form", "人脸识别个人信息采集系统"))
        self.pb_checkInfo.setText(_translate("Form", "查看人脸数据集"))
        self.pb_takePhoto.setText(_translate("Form", "拍照"))
        self.label_face_num.setText(_translate("Form", "已采集人脸数"))
        self.label_face_num_2.setText(_translate("Form", "图片数"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
